# https://docs.docker.com/compose/compose-file/05-services/
x-mongo-image: &mongo-image
    image: mongo:8.0
x-redis-image: &redis-image
    image: redis:7.4

x-logging: &default-logging
    options:
        max-size: '10m'
        max-file: '3'

x-mongo-common: &mongo-common
    <<: *mongo-image
    profiles: ['infra']
    logging: *default-logging
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    command: 'mongod --replSet ${MONGO_DB_REPLICA_NAME} --keyFile /etc/mongodb/mongodb.key --bind_ip_all'
    volumes:
        - mongodb_key:/etc/mongodb
    networks:
        - default
    restart: always
    depends_on:
        - mongo-key-generator
    healthcheck:
        test:
            [
                'CMD',
                'mongosh',
                '--quiet',
                '-u',
                $MONGO_DB_USERNAME,
                '-p',
                $MONGO_DB_PASSWORD,
                '--authenticationDatabase',
                'admin',
                '--eval',
                'rs.isMaster().ismaster || rs.isMaster().secondary'
            ]
        interval: 5s
        timeout: 5s
        retries: 5

x-redis-common: &redis-common
    <<: *redis-image
    command:
        [
            'redis-server',
            '--port',
            $REDIS_PORT,
            '--cluster-enabled',
            'yes',
            '--cluster-config-file',
            'nodes.conf',
            '--cluster-node-timeout',
            '5000',
            '--appendonly',
            'yes',
            '--requirepass',
            $REDIS_PASSWORD,
            '--masterauth',
            $REDIS_PASSWORD
        ]
    profiles: ['infra']
    logging: *default-logging
    networks:
        - default
    restart: always
    healthcheck:
        test: ['CMD', 'redis-cli', '-a', $REDIS_PASSWORD, 'ping']
        interval: 5s
        timeout: 5s
        retries: 5

x-apps-common: &apps-common
    profiles: ['apps']
    logging: *default-logging
    environment:
        - NODE_ENV=production
    env_file: .env.test
    networks:
        - default

services:
    redis1:
        <<: *redis-common
        container_name: ${REDIS_HOST1}
    redis2:
        <<: *redis-common
        container_name: ${REDIS_HOST2}
    redis3:
        <<: *redis-common
        container_name: ${REDIS_HOST3}
    redis4:
        <<: *redis-common
        container_name: ${REDIS_HOST4}
    redis5:
        <<: *redis-common
        container_name: ${REDIS_HOST5}
    redis6:
        <<: *redis-common
        container_name: ${REDIS_HOST6}
    redis-cluster-setup:
        <<: *redis-image
        container_name: ${PROJECT_NAME}-redis-cluster-setup
        profiles: ['infra']
        depends_on:
            redis1:
                condition: service_healthy
            redis2:
                condition: service_healthy
            redis3:
                condition: service_healthy
            redis4:
                condition: service_healthy
            redis5:
                condition: service_healthy
            redis6:
                condition: service_healthy
        command: >
            sh -c "echo 'yes' | redis-cli -a $REDIS_PASSWORD --cluster create
            redis1:$REDIS_PORT
            redis2:$REDIS_PORT
            redis3:$REDIS_PORT
            redis4:$REDIS_PORT
            redis5:$REDIS_PORT
            redis6:$REDIS_PORT
            --cluster-replicas 1"
        networks:
            - default

    mongo-key-generator:
        <<: *mongo-image
        container_name: ${PROJECT_NAME}-mongo-key-generator
        profiles: ['infra']
        command: sh -c "openssl rand -base64 768 > mongodb.key && chmod 400 mongodb.key && chown mongodb:mongodb mongodb.key"
        volumes:
            - mongodb_key:/mongodb_key
        working_dir: /mongodb_key
    mongo1:
        <<: *mongo-common
        container_name: ${MONGO_DB_HOST1}
    mongo2:
        <<: *mongo-common
        container_name: ${MONGO_DB_HOST2}
    mongo3:
        <<: *mongo-common
        container_name: ${MONGO_DB_HOST3}
    mongo-cluster-setup:
        <<: *mongo-image
        container_name: ${PROJECT_NAME}-mongo-cluster-setup
        profiles: ['infra']
        depends_on:
            mongo1:
                condition: service_healthy
            mongo2:
                condition: service_healthy
            mongo3:
                condition: service_healthy
        command: >
            sh -c "
            mongosh --host ${MONGO_DB_HOST1} --port ${MONGO_DB_PORT} -u ${MONGO_DB_USERNAME} -p ${MONGO_DB_PASSWORD} --authenticationDatabase admin --eval
            \"rs.initiate({
                _id: \\\"${MONGO_DB_REPLICA_NAME}\\\",
                members: [
                    {_id: 0, host: \\\"${MONGO_DB_HOST1}\\\"},
                    {_id: 1, host: \\\"${MONGO_DB_HOST2}\\\"},
                    {_id: 2, host: \\\"${MONGO_DB_HOST3}\\\"}
                ]
            })\"

            MONGO_URI=\"mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@${MONGO_DB_HOST1}:${MONGO_DB_PORT},${MONGO_DB_HOST2}:${MONGO_DB_PORT},${MONGO_DB_HOST3}:${MONGO_DB_PORT}\"

            until mongosh \"$${MONGO_URI}/?authSource=admin&replicaSet=${MONGO_DB_REPLICA_NAME}\" --eval \"db.test.insertOne({test: 'test'})\" ; do
              echo 'The cluster is not ready yet. Retrying in 1 second.';
              sleep 1;
            done;
            "
        networks:
            - default

    gateway:
        <<: *apps-common
        build:
            context: .
            args:
                APPNAME: gateway
        image: ${PROJECT_NAME}-gateway
        container_name: ${PROJECT_NAME}-gateway
        ports:
            - 3000:3000
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - ./_output/logs/gateway:/app/_output/logs
            - ./_output/uploads:/app/_output/uploads

    applications:
        <<: *apps-common
        build:
            context: .
            args:
                APPNAME: applications
                APP_PORT: 3002
        image: ${PROJECT_NAME}-applications
        container_name: ${PROJECT_NAME}-applications
        ports:
            - 3002:3002
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:3003/health']
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - ./_output/logs/applications:/app/_output/logs

    cores:
        <<: *apps-common
        build:
            context: .
            args:
                APPNAME: cores
                APP_PORT: 3004
        image: ${PROJECT_NAME}-cores
        container_name: ${PROJECT_NAME}-cores
        ports:
            - 3004:3004
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:3005/health']
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - ./_output/logs/cores:/app/_output/logs

    infrastructures:
        <<: *apps-common
        build:
            context: .
            args:
                APPNAME: infrastructures
        image: ${PROJECT_NAME}-infrastructures
        container_name: ${PROJECT_NAME}-infrastructures
        ports:
            - 3006:3006
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:3007/health']
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - ./_output/logs/infrastructures:/app/_output/logs
            - ./_output/uploads:/app/_output/uploads

    setup-apps:
        image: node:22-alpine
        container_name: ${PROJECT_NAME}-setup
        profiles: ['apps']
        depends_on:
            gateway:
                condition: service_healthy
            applications:
                condition: service_healthy
            cores:
                condition: service_healthy
            infrastructures:
                condition: service_healthy

networks:
    default:
        external: true
        name: ${PROJECT_NAME}

volumes:
    mongodb_key:
