x-mongo-image: &mongo-image
    image: mongo:8.0
x-redis-image: &redis-image
    image: redis:7.4

x-logging: &default-logging
    options:
        max-size: '10m'
        max-file: '3'

x-mongo-common: &mongo-common
    <<: *mongo-image
    profiles: ['infra']
    logging: *default-logging
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    command: 'mongod --replSet ${MONGO_DB_REPLICA_NAME} --keyFile /etc/mongodb/mongodb.key --bind_ip_all'
    volumes:
        - mongodb_key:/etc/mongodb
    networks:
        - default
    restart: always
    depends_on:
        - mongo-key-generator
    healthcheck:
        test:
            [
                'CMD',
                'mongosh',
                '--quiet',
                '-u',
                $MONGO_DB_USERNAME,
                '-p',
                $MONGO_DB_PASSWORD,
                '--authenticationDatabase',
                'admin',
                '--eval',
                'rs.isMaster().ismaster || rs.isMaster().secondary'
            ]
        interval: 5s
        timeout: 5s
        retries: 5

x-redis-common: &redis-common
    <<: *redis-image
    command:
        [
            'redis-server',
            '--port',
            $REDIS_PORT,
            '--cluster-enabled',
            'yes',
            '--cluster-config-file',
            'nodes.conf',
            '--cluster-node-timeout',
            '5000',
            '--appendonly',
            'yes',
            '--requirepass',
            $REDIS_PASSWORD,
            '--masterauth',
            $REDIS_PASSWORD
        ]
    profiles: ['infra']
    logging: *default-logging
    networks:
        - default
    restart: always
    healthcheck:
        test: ['CMD', 'redis-cli', '-a', $REDIS_PASSWORD, 'ping']
        interval: 5s
        timeout: 5s
        retries: 5

x-kafka-controller: &kafka-controller
    image: apache/kafka:3.9.0
    working_dir: /opt/kafka/bin
    profiles: ['infra']
    logging: *default-logging
    networks:
        - default

x-kafka-controller-env: &kafka-controller-env
    KAFKA_PROCESS_ROLES: controller
    KAFKA_LISTENERS: CONTROLLER://:9093
    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    KAFKA_CONTROLLER_QUORUM_VOTERS: 1@${PROJECT_NAME}-kafka-ctl-1:9093,2@${PROJECT_NAME}-kafka-ctl-2:9093,3@${PROJECT_NAME}-kafka-ctl-3:9093
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

x-kafka-broker: &kafka-broker
    image: apache/kafka:3.9.0
    working_dir: /opt/kafka/bin
    depends_on:
        - kafka-controller-1
        - kafka-controller-2
        - kafka-controller-3
    profiles: ['infra']
    logging: *default-logging
    networks:
        - default

x-kafka-broker-env: &kafka-broker-env
    KAFKA_PROCESS_ROLES: broker
    KAFKA_LISTENERS: 'PLAINTEXT://:${KAFKA_PORT},PLAINTEXT_HOST://:9092'
    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    KAFKA_CONTROLLER_QUORUM_VOTERS: 1@${PROJECT_NAME}-kafka-ctl-1:9093,2@${PROJECT_NAME}-kafka-ctl-2:9093,3@${PROJECT_NAME}-kafka-ctl-3:9093
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

x-apps-common: &apps-common
    profiles: ['apps']
    logging: *default-logging
    environment:
        - NODE_ENV=production
    env_file: .env.test
    networks:
        - default

services:
    redis1:
        <<: *redis-common
        container_name: ${REDIS_HOST1}
    redis2:
        <<: *redis-common
        container_name: ${REDIS_HOST2}
    redis3:
        <<: *redis-common
        container_name: ${REDIS_HOST3}
    redis4:
        <<: *redis-common
        container_name: ${REDIS_HOST4}
    redis5:
        <<: *redis-common
        container_name: ${REDIS_HOST5}
    redis6:
        <<: *redis-common
        container_name: ${REDIS_HOST6}
    redis-setup:
        <<: *redis-image
        container_name: ${PROJECT_NAME}-redis-setup
        profiles: ['infra']
        depends_on:
            redis1:
                condition: service_healthy
            redis2:
                condition: service_healthy
            redis3:
                condition: service_healthy
            redis4:
                condition: service_healthy
            redis5:
                condition: service_healthy
            redis6:
                condition: service_healthy
        command: >
            sh -c "echo 'yes' | redis-cli -a $REDIS_PASSWORD --cluster create
            redis1:$REDIS_PORT
            redis2:$REDIS_PORT
            redis3:$REDIS_PORT
            redis4:$REDIS_PORT
            redis5:$REDIS_PORT
            redis6:$REDIS_PORT
            --cluster-replicas 1"
        networks:
            - default

    mongo-key-generator:
        <<: *mongo-image
        container_name: ${PROJECT_NAME}-mongo-key-generator
        profiles: ['infra']
        command: sh -c "openssl rand -base64 768 > mongodb.key && chmod 400 mongodb.key && chown mongodb:mongodb mongodb.key"
        volumes:
            - mongodb_key:/mongodb_key
        working_dir: /mongodb_key
    mongo1:
        <<: *mongo-common
        container_name: ${MONGO_DB_HOST1}
    mongo2:
        <<: *mongo-common
        container_name: ${MONGO_DB_HOST2}
    mongo3:
        <<: *mongo-common
        container_name: ${MONGO_DB_HOST3}
    mongo-setup:
        <<: *mongo-image
        container_name: ${PROJECT_NAME}-mongo-setup
        profiles: ['infra']
        depends_on:
            mongo1:
                condition: service_healthy
            mongo2:
                condition: service_healthy
            mongo3:
                condition: service_healthy
        command: >
            sh -c "
            mongosh --host ${MONGO_DB_HOST1} --port ${MONGO_DB_PORT} -u ${MONGO_DB_USERNAME} -p ${MONGO_DB_PASSWORD} --authenticationDatabase admin --eval
            \"rs.initiate({
                _id: \\\"${MONGO_DB_REPLICA_NAME}\\\",
                members: [
                    {_id: 0, host: \\\"${MONGO_DB_HOST1}\\\"},
                    {_id: 1, host: \\\"${MONGO_DB_HOST2}\\\"},
                    {_id: 2, host: \\\"${MONGO_DB_HOST3}\\\"}
                ]
            })\"

            MONGO_URI=\"mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@${MONGO_DB_HOST1}:${MONGO_DB_PORT},${MONGO_DB_HOST2}:${MONGO_DB_PORT},${MONGO_DB_HOST3}:${MONGO_DB_PORT}\"

            until mongosh \"$${MONGO_URI}/?authSource=admin&replicaSet=${MONGO_DB_REPLICA_NAME}\" --eval \"db.test.insertOne({test: 'test'})\" ; do
              echo 'The cluster is not ready yet. Retrying in 1 second.';
              sleep 1;
            done;
            "
        networks:
            - default

    kafka-controller-1:
        <<: *kafka-controller
        container_name: ${PROJECT_NAME}-kafka-ctl1
        environment:
            <<: *kafka-controller-env
            KAFKA_NODE_ID: 1
    kafka-controller-2:
        <<: *kafka-controller
        container_name: ${PROJECT_NAME}-kafka-ctl2
        environment:
            <<: *kafka-controller-env
            KAFKA_NODE_ID: 2
    kafka-controller-3:
        <<: *kafka-controller
        container_name: ${PROJECT_NAME}-kafka-ctl3
        environment:
            <<: *kafka-controller-env
            KAFKA_NODE_ID: 3
    kafka-broker-1:
        <<: *kafka-broker
        container_name: ${KAFKA_BROKER1}
        ports:
            - 29092:9092
        environment:
            <<: *kafka-broker-env
            KAFKA_NODE_ID: 4
            KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://${KAFKA_BROKER1}:${KAFKA_PORT},PLAINTEXT_HOST://localhost:29092'
        healthcheck:
            test: /opt/kafka/bin/kafka-client-metrics.sh --bootstrap-server ${KAFKA_BROKER1}:${KAFKA_PORT} --list
            interval: 30s
            timeout: 10s
    kafka-broker-2:
        <<: *kafka-broker
        container_name: ${KAFKA_BROKER2}
        ports:
            - 39092:9092
        environment:
            <<: *kafka-broker-env
            KAFKA_NODE_ID: 5
            KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://${KAFKA_BROKER2}:${KAFKA_PORT},PLAINTEXT_HOST://localhost:39092'
        healthcheck:
            test: /opt/kafka/bin/kafka-client-metrics.sh --bootstrap-server ${KAFKA_BROKER2}:${KAFKA_PORT} --list
            interval: 30s
            timeout: 10s
    kafka-broker-3:
        <<: *kafka-broker
        container_name: ${KAFKA_BROKER3}
        ports:
            - 49092:9092
        environment:
            <<: *kafka-broker-env
            KAFKA_NODE_ID: 6
            KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://${KAFKA_BROKER3}:${KAFKA_PORT},PLAINTEXT_HOST://localhost:49092'
        healthcheck:
            test: /opt/kafka/bin/kafka-client-metrics.sh --bootstrap-server ${KAFKA_BROKER3}:${KAFKA_PORT} --list
            interval: 30s
            timeout: 10s
    gateway:
        <<: *apps-common
        build:
            context: .
            args:
                APP_NAME: gateway
        image: ${SERVICE_GATEWAY_HOST}
        container_name: ${SERVICE_GATEWAY_HOST}
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:${SERVICE_GATEWAY_PORT}/health']
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - ./_output/logs/gateway:/app/_output/logs
            - ./_output/uploads:/app/_output/uploads
    applications:
        <<: *apps-common
        build:
            context: .
            args:
                APP_NAME: applications
        image: ${PROJECT_NAME}-apps
        container_name: ${PROJECT_NAME}-apps
        healthcheck:
            test:
                ['CMD', 'curl', '-f', 'http://localhost:${SERVICE_APPLICATIONS_HEALTH_PORT}/health']
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - ./_output/logs/applications:/app/_output/logs
    cores:
        <<: *apps-common
        build:
            context: .
            args:
                APP_NAME: cores
        image: ${PROJECT_NAME}-cores
        container_name: ${PROJECT_NAME}-cores
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:${SERVICE_CORES_HEALTH_PORT}/health']
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - ./_output/logs/cores:/app/_output/logs
    infrastructures:
        <<: *apps-common
        build:
            context: .
            args:
                APP_NAME: infrastructures
        image: ${PROJECT_NAME}-infras
        container_name: ${PROJECT_NAME}-infras
        healthcheck:
            test:
                [
                    'CMD',
                    'curl',
                    '-f',
                    'http://localhost:${SERVICE_INFRASTRUCTURES_HEALTH_PORT}/health'
                ]
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - ./_output/logs/infrastructures:/app/_output/logs
            - ./_output/uploads:/app/_output/uploads
    apps-setup:
        image: node:22-alpine
        container_name: ${PROJECT_NAME}-apps-setup
        profiles: ['apps']
        depends_on:
            gateway:
                condition: service_healthy
            applications:
                condition: service_healthy
            cores:
                condition: service_healthy
            infrastructures:
                condition: service_healthy

networks:
    default:
        external: true
        name: ${PROJECT_NAME}

volumes:
    mongodb_key:


# docker exec --workdir /opt/kafka/bin/ -it nest-kafka1 sh
# ./kafka-topics.sh --bootstrap-server nest-kafka1:19092,nest-kafka2:19092,nest-kafka3:19092 --create --topic test-topic
# ./kafka-console-producer.sh --bootstrap-server nest-kafka1:19092,nest-kafka2:19092,nest-kafka3:19092 --topic test-topic
# ./kafka-console-consumer.sh --bootstrap-server nest-kafka1:19092,nest-kafka2:19092,nest-kafka3:19092 --topic test-topic --from-beginning
